Repository Buffet-IT-Services/CycleInvoice, pull requests merged in 2025-06, with the labels that each got.

#24 implemented S3
  .github/workflows/github-action-tests.yml
  .idea/dataSources.xml
  common/tests.py
  common/tests/__init__.py
  common/tests/models/__init__.py
  cycle_invoice/settings.py
  requirements.txt
  sale/models.py
  sale/tests/models/test_document_item_product.py
  sale/tests/models/test_document_item_work.py
Labels: enhancement

#31 Setup Subscription to create new DocumentItems
  .gitignore
  .idea/CycleInvoice.iml
  .idea/dataSources.xml
  .idea/runConfigurations/Celery_Beat.xml
  .idea/runConfigurations/Celery_Worker.xml
  .idea/runConfigurations/Django___Celery.xml
  .idea/runConfigurations/Test_incl__Coverage.xml
  accounting/migrations/0001_initial.py
  accounting/migrations/0002_historicaltransaction_transaction_historicalpayment.py
  accounting/migrations/0002_initial.py
  accounting/validators.py
  contact/migrations/0001_initial.py
  contact/migrations/0002_customer_remove_contact_id_remove_organisation_id_and_more.py
  contact/migrations/0003_alter_customer_options.py
  contact/migrations/0004_remove_contact_address_remove_organisation_address_and_more.py
  contact/migrations/0005_address_disabled_historicaladdress_disabled.py
  contact/models.py
  contact/tests/models/test_customer.py
  cycle_invoice/__init__.py
  cycle_invoice/celery.py
  cycle_invoice/settings.py
  requirements.txt
  sale/admin.py
  sale/migrations/0001_initial.py
  sale/migrations/0002_historicalsubscription_subscription.py
  sale/migrations/0002_remove_historicalsubscription_end_date_and_more.py
  sale/migrations/0003_documentinvoice_documentitem_and_more.py
  sale/migrations/0003_rename_canceled_date_historicalsubscription_cancelled_date_and_more.py
  sale/migrations/0004_alter_documentitem_invoice.py
  sale/migrations/0004_alter_historicalsubscriptionproduct_recurrence_and_more.py
  sale/migrations/0005_rename_documentproduct_documentitemproduct_and_more.py
  sale/migrations/0006_historicalproduct_description_product_description.py
  sale/migrations/0007_documentitemwork_description_and_more.py
  sale/migrations/0008_rename_description_documentitemwork_comment_and_more.py
  sale/migrations/0009_remove_documentitem_item_group_and_more.py
  sale/migrations/0010_historicalworktype_price_per_hour_and_more.py
  sale/migrations/0011_remove_worktypeprice_work_type_and_more.py
  sale/migrations/0012_documentitem_customer_and_more.py
  sale/migrations/0013_alter_documentitem_invoice.py
  sale/models.py
  sale/services/__init__.py
  sale/services/subscription.py
  sale/tasks.py
  sale/tests/models/test_document_item_subscription.py
  sale/tests/models/test_subscription.py
  sale/tests/models/test_subscription_product.py
  sale/tests/services/__init__.py
  sale/tests/services/test_subscription.py
  sale/tests/test_tasks.py
  vehicle/migrations/0001_initial.py
  vehicle/migrations/0002_alter_historicalvehicle_name_external_and_more.py
  web/migrations/0001_initial.py
Labels: enhancement

#25 Add invoice PDF generation with QR bill support
  .gitignore
  .idea/inspectionProfiles/Default.xml
  accounting/migrations/0001_initial.py
  accounting/migrations/0002_initial.py
  accounting/tests/models/test_account.py
  contact/migrations/0001_initial.py
  contact/models.py
  contact/tests/models/test_address.py
  cycle_invoice/settings.py
  pyproject.toml
  requirements.txt
  sale/admin.py
  sale/migrations/0001_initial.py
  sale/migrations/0002_alter_documentitem_product_and_more.py
  sale/migrations/0002_remove_historicalsubscription_end_date_and_more.py
  sale/migrations/0003_documentitem_work_type_and_more.py
  sale/migrations/0003_rename_canceled_date_historicalsubscription_cancelled_date_and_more.py
  sale/migrations/0004_alter_historicalsubscriptionproduct_recurrence_and_more.py
  sale/migrations/0004_documentitem_item_type_and_more.py
  sale/models.py
  sale/services/subscription.py
  sale/tests/models/test_document_invoice.py
  sale/tests/models/test_document_item.py
  sale/tests/models/test_document_item_product.py
  sale/tests/models/test_document_item_subscription.py
  sale/tests/models/test_document_item_work.py
  sale/tests/services/test_subscription.py
  sale/tests/utils/__init__.py
  sale/tests/utils/test_invoice_pdf_generation.py
  sale/tests/utils/test_swiss_qr.py
  sale/utils/__init__.py
  sale/utils/invoice_pdf_generation.py
  sale/utils/swiss_qr.py
  sale/views.py
  static/sale/images/call.svg
  static/sale/images/email.svg
  static/sale/images/footer.svg
  static/sale/images/header.svg
  static/sale/images/logo.svg
  static/sale/images/user.svg
  static/sale/images/web.svg
  templates/sale/invoice.html
  templates/sale/qr_code.html
  vehicle/admin.py
  vehicle/migrations/0001_initial.py
  vehicle/models.py
  vehicle/tests/models/test_document_item_kilometers.py
  vehicle/tests/models/test_vehicle.py
  web/migrations/0001_initial.py
Labels: enhancement

#38 moved from pypdf2 to pypdf
  requirements.txt
  sale/tests/utils/test_invoice_pdf_generation.py
  sale/utils/invoice_pdf_generation.py
Labels: bug

#48 different small fixes
  cycle_invoice/api/urls.py
  cycle_invoice/contact/filters.py
  cycle_invoice/contact/migrations/0002_remove_address_disabled_and_more.py
  cycle_invoice/contact/models.py
  cycle_invoice/contact/selectors/__init__.py
  cycle_invoice/contact/selectors/address.py
  cycle_invoice/contact/selectors/contact.py
  cycle_invoice/contact/selectors/customer.py
  cycle_invoice/contact/selectors/organisation.py
  cycle_invoice/contact/tests/models/test_organisation.py
  cycle_invoice/contact/tests/selectors/__init__.py
  cycle_invoice/contact/tests/selectors/test_address.py
  cycle_invoice/contact/tests/selectors/test_contact.py
  cycle_invoice/contact/tests/selectors/test_customer.py
  cycle_invoice/contact/tests/selectors/test_organisation.py
  cycle_invoice/sale/api/document_invoice.py
  cycle_invoice/sale/selectors/__init__.py
  cycle_invoice/sale/selectors/document_invoice.py
  cycle_invoice/sale/services/document_invoice.py
  cycle_invoice/sale/tests/selectors/__init__.py
  cycle_invoice/sale/tests/selectors/test_document_invoice.py
  cycle_invoice/sale/urls.py
Labels: bug, enhancement

#70 60 prevent pk from showing only UUID
  .idea/dataSources.xml
  .idea/runConfigurations/Test_Fast.xml
  cycle_invoice/accounting/migrations/0003_account_accounting_account_prevent_soft_delete_if_default_buy_or_sell.py
  cycle_invoice/accounting/models.py
  cycle_invoice/accounting/tests/models/test_account.py
  cycle_invoice/common/models.py
  cycle_invoice/common/selectors.py
  cycle_invoice/common/services.py
  cycle_invoice/common/tests/test_models.py
  cycle_invoice/common/tests/test_selectors.py
  cycle_invoice/contact/admin.py
  cycle_invoice/sale/api/document_invoice.py
  cycle_invoice/sale/selectors/document_invoice.py
  cycle_invoice/sale/tests/api/test_document_invoice.py
  cycle_invoice/sale/urls.py
  requirements/local.txt
Labels: bug
